Add extraction/re-packing of rootfs
daniestevez/pluto-firmware-modifications pull request #3
Opened 2022-11-07 03:16 UTC by DeonMarais64

2022-11-07 18:42 UTC, daniestevez requested changes
Thanks. I've spotted a small problem with a link. Otherwise this is ready to go.

By the way, there was no need to close #2 and open a new pull request. You can add additional commits or force-push to the branch of a pull request.

2022-11-07 18:42 UTC, daniestevez commented on README.md
> +[`below`](https://github.com/daniestevez/pluto-firmware-modifications/edit/main/README.md#extraction-and-re-packing-of-the-rootfs)
This link points to the "edit" page. The correct link would be https://github.com/daniestevez/pluto-firmware-modifications/blob/main/README.md#extraction-of-the-pluto-firmware-image

I don't know if it's possible to include a relative link to a section, as in `[below](#extraction-and-re-packing-of-the-rootfs)`.

2022-11-08 00:56 UTC, DeonMarais64 commented
The git review process and PR updates resulting from it is something that I am yet to master. Please let me know if I need to do anything further.

2022-11-08 20:50 UTC, daniestevez approved these changes
Thank you! Now this looks good.

No worries. It gets some time to get used to all the features of Github and the usage of git. I realized that there is a Github feature to suggest modifications that I could have used to make this process easier.

2022-11-08 20:50 UTC, merged